### ISSUE TITLE
Remove build code and only leave the dart code

### ISSUE THREAD

**Issue by salahmak** [RaidOuahioune/flight-app#1]
Hi,

I have noticed that you have pushed the production code (after being compiled) to the github repo, which is not good, because it is not needed (since it is auto-generated by flutter's compiler). So instead unstage the generated builds and only leave the dart code and put instructions in the README.md on how to build it on your own machine.

Anyways, the app looks good, good job!

**Comment by RaidOuahioune** [comment]
Understood .thank you  for your feedback !
